nodeapi:
  build: server/
  restart: always
  container_name: nodeapi
  ports: ["9090:9090"]
  environment:
    - NODE_ENV=dev
    - APP_PORT=9090
    - MONGO='mongodb://mongodb:27017/imaginary'
  volumes:
    - "./server/src:/var/www/app/src"
  links:
    - mongodb
mongodb:
  restart: always
  image: "mongo:latest"
  volumes:
    - "./server/mongodata:/data/db"
  ports: ["27017:27017"]